site_name: ROS Switch
repo_url: https://github.com/Baxterminator/ros_switch
site_description: Documentation of the rosswitch application that allow to easily switch ROS environments
site_author: Meltwin
copyright: © 2024 - Meltwin
docs_dir: docs
site_dir: build
extra_css:
  - assets/extra.css
nav:
  - Home: index.md
  - Install:
      - install/compat.md
      - install/index.md
  - Usage: cmd/index.md
  - config/index.md
  - yaml/index.md
theme:
  name: material
  favicon: assets/logo_only.svg
  logo: assets/logo_only.svg
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
      primary: black
      accent: teal

    # Palette toggle for dark mode
    - scheme: slate
      logo: assets/Logo_WR.svg
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: teal
      accent: cyan
  features:
    - content.code.copy
    - content.code.select
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - md_in_html
  - footnotes
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - admonition
  - pymdownx.details