#!/bin/bash

# Get the script directory
SOURCE=${BASH_SOURCE[0]}
while [ -L "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR=$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )
  SOURCE=$(readlink "$SOURCE")
  [[ $SOURCE != /* ]] && SOURCE=$DIR/$SOURCE # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
DIR=$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )

# Get the script parameters to push it
PARAMS=""
for argv in "$@"
do
    PARAMS="$PARAMS $argv"
done

# Call the python script
OUT=$(cd $DIR; python3 bin/profiles.py $PARAMS)

# Act upon the output
if [[ "$OUT" =~ ^"=" ]]; then
  echo "$OUT"
elif [[ ! -z "$OUT" ]]; then
  echo "load file"
fi